version: '3.9'

services:
    db:
        image: postgres
        container_name: postgres
        restart: unless-stopped
        ports:
            - 5433:5432
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
